name: flutter_templating
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # for state managment
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.4

  # for dates manipulation
  jiffy: ^6.1.0

  # forms
  reactive_forms: ^14.3.0
  reactive_raw_autocomplete: ^0.6.0
  reactive_file_picker: ^0.12.0
  reactive_date_time_picker: ^0.6.1 
  reactive_multi_select_flutter: ^0.0.1

  uuid: ^3.0.7
  collection: ^1.17.0
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  universal_platform: ^1.0.0+1
  multiselect: ^0.0.4
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.1.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
